export enum FileType {
  UPLOADED_RECORDING = "UPLOADED_RECORDING",
  PROCESSED_RECORDING = "PROCESSED_RECORDING",
  SPEAKER_SEGMENTS = "SPEAKER_SEGMENTS",
  UNDIARIZED_TRANSCRIPT = "UNDIARIZED_TRANSCRIPT",
  DIARIZED_TRANSCRIPT_SEGMENTS = "DIARIZED_TRANSCRIPT_SEGMENTS",
  PARAPHRASED_SPEAKER_TURNS = "PARAPHRASED_SPEAKER_TURNS"
}
