export enum FileType {
  UPLOADED_CALL = "UPLOADED_CALL",
  PROCESSED_CALL = "PROCESSED_CALL",
  SPEAKER_SEGMENTS = "SPEAKER_SEGMENTS",
  UNDIARIZED_TRANSCRIPT = "UNDIARIZED_TRANSCRIPT",
  DIARIZED_TRANSCRIPT_SEGMENTS = "DIARIZED_TRANSCRIPT_SEGMENTS",
  PARAPHRASED_SPEAKER_TURNS = "PARAPHRASED_SPEAKER_TURNS"
}
