export enum CollectionName {
  DIARIZED_TRANSCRIPT_SEGMENT = "DiarizedTranscriptSegment",
  CALENDAR_MEETING = "CalendarMeeting",
  USER = "User",
  ORGANISATION = "Organisation",
  MEMBERSHIP = "Membership",
  INVITE = "Invite",
  CALL = "Call",
  OAUTH_CONNECTION = "OauthConnection",
  PIPELINE_TASK = "PipelineTask",
  PARAPHRASED_SPEAKER_TURN = "ParaphrasedSpeakerTurn",
  SPEAKER_ALIAS = "SpeakerAlias",
  INSTANT_MESSAGE = "InstantMessage",
  INSTANT_MESSAGE_CHANNEL = "InstantMessageChannel",
  INSTANT_MESSAGE_CHANNEL_MEMBERSHIP = "InstantMessageChannelMembership",
  CALL_SUMMARY = "CallSummary",
  SYNCED_DATA = "SyncedData",
  DATA_EXTRACTION = "DataExtraction",
  OAUTH_STATE = "OauthState",
}